// Store-specific offers and promotional deals linked to store products and aisles
export const STORE_OFFERS = [
  {
    id: 'off-milk',
    productId: 7,
    productName: 'Milk',
    title: 'Farm Fresh Whole Milk',
    description: 'Fresh pasteurized whole milk, rich and chilled daily.',
    discount: '20% OFF',
    discountPrice: 52,
    originalPrice: 65,
    category: 'Dairy',
    aisle: 'Aisle A4',
    shelf: 'Shelf 1',
    floor: 'Floor 1',
    nodeId: 'A4',
    emoji: '🥛',
    badge: '20% OFF',
    badgeColor: 'bg-blue-600',
    expiresIn: 'Ends today'
  },
  {
    id: 'off-pasta',
    productId: 16,
    productName: 'Pasta',
    title: 'Italian Penne Rigate',
    description: '100% durum wheat semolina gourmet pasta.',
    discount: '15% OFF',
    discountPrice: 72,
    originalPrice: 85,
    category: 'Grains & Staples',
    aisle: 'Aisle A2',
    shelf: 'Shelf 1',
    floor: 'Floor 1',
    nodeId: 'A2',
    emoji: '🍝',
    badge: '15% OFF',
    badgeColor: 'bg-amber-600',
    expiresIn: 'Flash Deal'
  },
  {
    id: 'off-cheese',
    productId: 17,
    productName: 'Cheese',
    title: 'Artisan Cheddar Block',
    description: 'Aged sharp cheddar cheese for pasta, sandwiches & snacking.',
    discount: '10% OFF',
    discountPrice: 126,
    originalPrice: 140,
    category: 'Dairy',
    aisle: 'Aisle A4',
    shelf: 'Shelf 2',
    floor: 'Floor 1',
    nodeId: 'A4',
    emoji: '🧀',
    badge: '10% OFF',
    badgeColor: 'bg-emerald-600',
    expiresIn: 'Limited Stock'
  },
  {
    id: 'off-shampoo',
    productId: 5,
    productName: 'Shampoo',
    title: 'Nourishing Keratin Shampoo',
    description: 'Salon moisture balance formula with essential oils.',
    discount: '25% OFF',
    discountPrice: 157,
    originalPrice: 210,
    category: 'Personal Care',
    aisle: 'Aisle B3',
    shelf: 'Shelf 1',
    floor: 'Floor 1',
    nodeId: 'B3',
    emoji: '🧴',
    badge: '25% OFF',
    badgeColor: 'bg-purple-600',
    expiresIn: 'Special Offer'
  },
  {
    id: 'off-toothpaste',
    productId: 1,
    productName: 'Toothpaste',
    title: 'Total Care Whitening',
    description: 'Cavity protection and fresh mint breath shield.',
    discount: '15% OFF',
    discountPrice: 95,
    originalPrice: 120,
    category: 'Personal Care',
    aisle: 'Aisle B2',
    shelf: 'Shelf 1',
    floor: 'Floor 1',
    nodeId: 'B2',
    emoji: '🪥',
    badge: '15% OFF',
    badgeColor: 'bg-indigo-600',
    expiresIn: 'Popular'
  },
  {
    id: 'off-rice',
    productId: 3,
    productName: 'Rice',
    title: 'Premium Basmati Rice',
    description: 'Save $70 on 5kg royal long grain harvest rice.',
    discount: '$70 OFF',
    discountPrice: 280,
    originalPrice: 350,
    category: 'Grains & Staples',
    aisle: 'Aisle A1',
    shelf: 'Shelf 1',
    floor: 'Floor 1',
    nodeId: 'A1',
    emoji: '🍚',
    badge: 'Best Value',
    badgeColor: 'bg-blue-500',
    expiresIn: 'Today only'
  },
  {
    id: 'off-oil',
    productId: 4,
    productName: 'Cooking Oil',
    title: 'Pure Sunflower Oil',
    description: 'Heart-healthy cholesterol-free cooking oil.',
    discount: '10% OFF',
    discountPrice: 148,
    originalPrice: 165,
    category: 'Grains & Staples',
    aisle: 'Aisle C2',
    shelf: 'Shelf 2',
    floor: 'Floor 2',
    nodeId: 'C2',
    emoji: '🫗',
    badge: 'Floor 2 Special',
    badgeColor: 'bg-amber-500',
    expiresIn: 'While stocks last'
  }
];
